export type Item = {
  id: number;
  code: string;
  barcode: string;
  accountNumber: null | number;
  name: string;
  printName: string;
  hideOnConsultation: boolean;
  price: number;
  priceWithVat: number;
  minimumPrice: null | number;
  minimumPriceWithVat: null | number;
  wholesalePrice: number;
  wholesalerDiscount: number;
  producerDiscount: number;
  specialDiscount: number;
  marginPercent: number;
  vatGroup: number;
  invoiceGroup: null | number;
  itemList: number;
  typeCode: number;
  polymorphicCtype: number;
  parent: null | string;
  parentAmount: number;
  instructions: null | string;
  archived: boolean;
  archivedDateTime: null | string;
  excludeDiscount: boolean;
  linkedItems: Array<number>;
  hideOnCounterSaleSearch: boolean;
  performedByRule: number;
  royaltyFee: null | string | number;
  created: string;
  modified: string;
  externalReportingCode: null | string;
  hideOnConsultationSearch: boolean;
};
