export type ProVetUser = {
  id: number;
  email: string;
  firstName: string;
  lastName: string;
  isActive: boolean;
  created: string;
  lastLogin: Date | null;
  userdetails: string;
  isStaff: boolean;
  groups: Array<number>;
  title: string;
  phone: string;
  veterinarianId: string;
  activeDepartment: number;
  initials: string;
  userType: number;
  areasOfExpertise: string;
  qualifications: string;
  picture: string | null;
  prescriberId: string | null;
  employeeId: string | null;
  vdsNumber: string | null;
  allDepartmentsActive: boolean;
  activeDepartments: Array<number>;
  homeDepartment: number | null;
  isCabinetUser: boolean;
  userDetails: number;
  updatedOn: any;
};
