version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    target-branch: "development"
  - package-ecosystem: "npm"
    directory: "apps/api.movetcare.com/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    target-branch: "development"
  - package-ecosystem: "npm"
    directory: "packages/tools/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
  - package-ecosystem: "npm"
    directory: "apps/movetcare.com"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
  - package-ecosystem: "npm"
    directory: "apps/app.movetcare.com"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
  - package-ecosystem: "npm"
    directory: "packages/constants"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "packages/eslint-config-custom"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "packages/schemas"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
  - package-ecosystem: "npm"
    directory: "packages/server"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
  - package-ecosystem: "npm"
    directory: "packages/types"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
  - package-ecosystem: "npm"
    directory: "packages/ui"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
  - package-ecosystem: "npm"
    directory: "packages/utilities"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "weekly"
    target-branch: "development"
