export type Appointment = {
  id: number;
  start: string;
  end: string;
  title: string;
  complaint: any;
  reason: string | null;
  instructions: string;
  user: string;
  additional_users: Array<string>;
  resources: Array<string>;
  client: string;
  patients: Array<string>;
  consultation: string | null;
  related_appointments: string | null;
  duration: number;
  notes: string;
  parent_appointment: string | null;
  child_appointments: Array<string>;
  active: number;
  department: string;
  ward: string | null;
  type: number;
  start_date: string;
  end_date: string;
  created: string;
  modified: string;
  created_user: string;
  modified_user: string;
  request_hash: string;
  telemedicine_url: string | null;
  telemedicine_url_master: string | null;
  telemedicine_room: string | null;
  cancellation_reason_text: string | null;
  cancellation_reason: string | null;
  no_show: boolean;
  client_notes: string | null;
  invoice_extras: string | null;
};
