name: Production Firestore Backup
on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: "0 5 * * *"
jobs:
  backup-firestore:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_PRODUCTION_LOGS }}
    steps:
      - uses: actions/checkout@master
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: Backup Firestore
        id: backup-firestore
        run: gcloud firestore export gs://movet-care-backups
      - uses: act10ns/slack@master
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: "#production-logs"
        if: always()
