name: PRODUCTION - Deploy Cloud Functions
on:
  push:
    branches:
      - disabled
    paths:
      - "apps/api.movetcare.com/**"
jobs:
  deploy:
    name: Deploy API
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_PRODUCTION }}
    steps:
      - name: Checkout Repo
        id: repo-checkout
        uses: actions/checkout@master
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Global Dependencies
        id: install-global-dependencies
        run: npm i -g firebase-tools pnpm
      - name: Install Dependencies
        id: install-dependencies
        run: pnpm install
      - name: Lint Cloud Functions
        id: lint
        run: pnpm -F api.movetcare.com run lint
      - name: Build Cloud Functions
        id: build
        run: pnpm -F api.movetcare.com run build
      - name: Deploy to Firebase
        id: deploy-cloud-functions
        run: firebase use movet-care --token "${{ secrets.FIREBASE_TOKEN_PRODUCTION}}" && firebase deploy --only functions --non-interactive -f --token "${{ secrets.FIREBASE_TOKEN_PRODUCTION}}"
      - name: Resync ProVet Configurations
        id: reset-provet-configs
        run: npm run init:config:prod
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: "#production-logs"
        if: always()
