name: Test Production Environments E2E
on: workflow_dispatch
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'pnpm'
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          record: true
          config-file: cypress.config.prod.js
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}