name: Test Production Environments E2E
on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
  - cron: "0 0 * * *"
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'pnpm'
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          record: true
          config-file: cypress.config.prod.js
          build: npx cypress info
        env:
          CYPRESS_TEST_ADMIN: false
          CYPRESS_APP_URL: "https://app.movetcare.com"
          CYPRESS_WEBSITE_URL: "https://movetcare.com"
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}
      - name: Print Cypress Cloud URL
        run: |
          echo Cypress finished with: ${{ steps.cypress.outcome }}
          echo See results at ${{ steps.cypress.outputs.dashboardUrl }}