name: (SCHEDULED) Test Production Environments E2E
on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
  - cron: "0 6 * * 0"
jobs:
  cypress_run:
    name: Cypress run
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_PRODUCTION_LOGS }}
    container: cypress/browsers:node12.18.3-chrome87-ff82
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: pnpm/action-setup@master
        with:
          version: 9.1.4
      - uses: actions/setup-node@master
        with:
          node-version: latest
      - name: Cypress run
        uses: cypress-io/github-action@master
        with:
          record: true
          parallel: true
          browser: chrome
          group: 'Chrome'
        env:
          CYPRESS_ENVIRONMENT: "production"
          CYPRESS_TEST_API_URL: "https://us-central1-movet-care.cloudfunctions.net/resetTestData"
          CYPRESS_APP_URL: "https://app.movetcare.com"
          CYPRESS_WEBSITE_URL: "https://movetcare.com"
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          CYPRESS_FAIL_FAST_PLUGIN: false
  wipe_test_data:
      name: Wipe Test Data
      needs: cypress_run
      runs-on: ubuntu-latest
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_PRODUCTION_LOGS }}
      steps:
        - name: Checkout
          uses: actions/checkout@master
        - name: Wipe Test Data from Database
          id: wipe-test-data
          run: npm run wipe:test:prod
        - uses: act10ns/slack@master
          with:
            status: ${{ job.status }}
            steps: ${{ toJson(steps) }}
            config: .github/config/slack.yml
            channel: "#production-logs"
          if: always()
