name: Test Production Environments E2E (W/FUNCTIONS))
on:
  push:
    branches:
      - main
    paths:
      - "apps/api.movetcare.com/**"
jobs:
  deploy:
    name: Deploy API via Firebase Cloud Functions
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_PRODUCTION }}
    steps:
      - name: Checkout Repo
        id: repo-checkout
        uses: actions/checkout@master
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'pnpm'
      - name: Install Global Dependencies
        id: install-global-dependencies
        run: pnpm add -g firebase-tools
      - name: Install Dependencies
        id: install-dependencies
        run: pnpm install
      - name: Lint Cloud Functions
        id: lint
        run: pnpm -F api.movetcare.com run lint
      - name: Build Cloud Functions
        id: build
        run: pnpm -F api.movetcare.com run build
      - name: Deploy to Firebase
        id: deploy-cloud-functions
        run: firebase use movet-care --token "${{ secrets.FIREBASE_TOKEN_PRODUCTION}}" && firebase deploy --only functions --non-interactive -f --token "${{ secrets.FIREBASE_TOKEN_PRODUCTION}}"
      - name: Resync ProVet Configurations
        id: reset-provet-configs
        run: npm run init:config:prod
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: "#production-logs"
        if: always()
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    needs: delpoy
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_PRODUCTION_LOGS }}
    container: cypress/browsers:node12.18.3-chrome87-ff82
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'pnpm'
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          record: true
          parallel: true
          browser: chrome
          group: 'Chrome'
        env:
          CYPRESS_ENVIRONMENT: "production"
          CYPRESS_TEST_API_URL: "https://us-central1-movet-care.cloudfunctions.net/resetTestData"
          CYPRESS_APP_URL: "https://app.movetcare.com"
          CYPRESS_WEBSITE_URL: "https://movetcare.com"
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}
      - name: Print Cypress Cloud URL
        run: |
          echo Cypress finished with: ${{ steps.cypress.outcome }}
          echo See results at ${{ steps.cypress.outputs.dashboardUrl }}
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: "#production-logs"
        if: always()
