name: STAGING - Deploy Firestore Security Rules
on:
  push:
    branches:
      - development
    paths:
      - "firestore.rules"
jobs:
  deploy:
    name: Deploy Firestore Security Rules
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_STAGING }}
    steps:
      - name: Checkout Repo
        id: repo-checkout
        uses: actions/checkout@v2.3.2
      - name: Deploy to Firebase
        id: deploy-rules
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore:rules --non-interactive -f
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_STAGING }}
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: "#development-feed"
        if: always()
