name: STAGING - Deploy Cloud Functions
on:
  push:
    branches:
      - disabled
    paths:
      - "apps/api.movetcare.com/**"
jobs:
  deploy:
    name: Deploy API
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_STAGING_LOGS }}
    strategy:
      matrix:
        node-version: [16]
    steps:
      - name: Checkout Repo
        id: repo-checkout
        uses: actions/checkout@master
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install Dependencies
        id: install-dependencies
        run: |
          cd apps/api.movetcare.com
          pnpm i
      - name: Deploy to Firebase
        id: deploy-functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --non-interactive -f
        env:
          PROJECT_ID: movet-care-staging
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_STAGING }}
      - name: Resync ProVet Configurations
        id: reset-provet-configs
        run: pnpm run init:config:stage
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: "#development-feed"
        if: always()
